"""Message broker for managing per-run event queues.

This module implements a Producer-Consumer pattern for LangGraph execution events.
It manages an independent event queue for each run, allowing multiple clients
to receive real-time streaming simultaneously.

Key Components:
- RunBroker: Manages the event queue and distribution for a single run.
- BrokerManager: Manages the lifecycle of multiple RunBroker instances.
- broker_manager: Global singleton instance.

Usage Example:
    from services.broker import broker_manager

    # Producer: Send an event
    broker = broker_manager.get_or_create_broker(run_id)
    await broker.put(event_id, payload)

    # Consumer: Receive an event
    async for event_id, payload in broker.aiter():
        print(f"Received: {event_id}")
"""

import asyncio
import contextlib
import logging
from collections.abc import AsyncIterator
from typing import Any

from .base_broker import BaseBrokerManager, BaseRunBroker

logger = logging.getLogger(__name__)


class RunBroker(BaseRunBroker):
    """Manages the event queue and distribution for a specific run.

    This is an event broker for a single LangGraph run.
    When a producer (the execution engine) sends an event via put(),
    multiple consumers (SSE streams) can receive the same event via aiter().

    Key Features:
    - asyncio.Queue-based event queuing.
    - Event broadcasting to multiple consumers (currently single consumer).
    - Detection of run completion and automatic cleanup.
    - Tracking of broker creation time (for auto-cleanup).

    Usage Patterns:
    - Producer: Sends events from execute_run_async().
    - Consumer: Receives events in streaming_service.stream_run_execution().
    """

    def __init__(self, run_id: str):
        self.run_id = run_id
        self.queue: asyncio.Queue[tuple[str, Any]] = asyncio.Queue()
        self.finished = asyncio.Event()  # Flag for run completion
        self._created_at = asyncio.get_event_loop().time()  # Creation time in seconds

    async def put(self, event_id: str, payload: Any) -> None:
        """Add an event to the broker queue (Producer role).

        Puts an event generated by the LangGraph execution engine into the queue.
        Consumers (SSE streams) will receive this event via aiter().

        Args:
            event_id (str): Unique event identifier (UUID).
            payload (Any): Event payload (e.g., event_type, data).

        Note:
            - Events cannot be added to a broker that is already finished.
            - Sending an "end" event automatically transitions the broker to a finished state.
        """
        if self.finished.is_set():
            logger.warning(f"Attempted to put event {event_id} into finished broker for run {self.run_id}")
            return

        await self.queue.put((event_id, payload))

        # Mark broker as finished upon detecting "end" event
        # payload is a tuple of the form (event_type, data)
        if isinstance(payload, tuple) and len(payload) >= 1 and payload[0] == "end":
            self.mark_finished()

    async def aiter(self) -> AsyncIterator[tuple[str, Any]]:
        """Iterate over events asynchronously (Consumer role)

        SSE streams call this method to get events one by one from the queue.
        If the queue is empty, it waits until a new event arrives.

        Workflow:
        1. Wait for an event with queue.get() (timeout 0.1 seconds)
        2. Yield (event_id, payload) tuple upon receiving an event
        3. Terminate iteration upon receiving an "end" event
        4. If timeout occurs, check if execution is complete and continue waiting or terminate

        Yields:
            tuple[str, Any]: (event_id, payload) pair

        Note:
            - A timeout is used to periodically check the execution completion status
            - Iteration terminates immediately upon receiving an "end" event
            - If execution is complete and the queue is empty, iteration terminates
        """
        while True:
            try:
                # Use a timeout to periodically check for completion
                event_id, payload = await asyncio.wait_for(self.queue.get(), timeout=0.1)
                yield event_id, payload

                # Immediately terminate upon detecting "end" event
                if isinstance(payload, tuple) and len(payload) >= 1 and payload[0] == "end":
                    break

            except TimeoutError:
                # If execution is complete and the queue is empty, terminate iteration
                if self.finished.is_set() and self.queue.empty():
                    break
                continue

    def mark_finished(self) -> None:
        """Mark the broker as finished

        Indicates that the execution has ended.
        aiter() will then terminate after consuming all remaining events in the queue.

        Note:
            - This is automatically called upon receiving an "end" event
            - Can also be called manually to force-terminate the broker
        """
        self.finished.set()
        logger.debug(f"Broker for run {self.run_id} marked as finished")

    def is_finished(self) -> bool:
        """Check if the broker is in a finished state

        Returns:
            bool: True if finished, False otherwise
        """
        return self.finished.is_set()

    def is_empty(self) -> bool:
        """Check if the queue is empty

        Returns:
            bool: True if the queue is empty, False otherwise
        """
        return self.queue.empty()

    def get_age(self) -> float:
        """Return the elapsed time since the broker was created

        Used in the auto-cleanup task to identify old brokers.

        Returns:
            float: Elapsed time since broker creation (in seconds)
        """
        return asyncio.get_event_loop().time() - self._created_at


class BrokerManager(BaseBrokerManager):
    """Lifecycle manager for multiple RunBroker instances

    This class manages brokers for all runs in the application.
    It creates and tracks an independent RunBroker for each run.

    Key features:
    - Per-run broker creation and retrieval
    - Automatic cleanup of finished brokers
    - Background cleanup task management
    - Memory leak prevention (deleting old brokers)

    Usage patterns:
    - Singleton instance: broker_manager
    - Start/stop cleanup task in FastAPI lifespan
    - Call get_or_create_broker() on run creation
    """

    def __init__(self) -> None:
        self._brokers: dict[str, RunBroker] = {}  # run_id -> RunBroker mapping
        self._cleanup_task: asyncio.Task | None = None  # Background cleanup task

    def get_or_create_broker(self, run_id: str) -> RunBroker:
        """Get or create a broker for a run

        If a broker for the specified run_id does not exist, a new one is created.
        If it already exists, the existing broker is returned.

        Args:
            run_id (str): Unique run identifier

        Returns:
            RunBroker: The broker instance for that run
        """
        if run_id not in self._brokers:
            self._brokers[run_id] = RunBroker(run_id)
            logger.debug(f"Created new broker for run {run_id}")
        return self._brokers[run_id]

    def get_broker(self, run_id: str) -> RunBroker | None:
        """Get an existing broker (returns None if not found)

        Args:
            run_id (str): Unique run identifier

        Returns:
            RunBroker | None: Broker instance or None
        """
        return self._brokers.get(run_id)

    def cleanup_broker(self, run_id: str) -> None:
        """Mark a broker for cleanup

        Marks the broker as finished but does not delete it immediately,
        as consumers might still be consuming events from the queue.

        Args:
            run_id (str): Unique run identifier

        Note:
            - Does not delete the broker immediately, only calls mark_finished()
            - Actual deletion is handled by the background cleanup task
        """
        if run_id in self._brokers:
            self._brokers[run_id].mark_finished()
            # Do not delete immediately as consumers might still be reading
            logger.debug(f"Marked broker for run {run_id} for cleanup")

    def remove_broker(self, run_id: str) -> None:
        """Completely remove a broker

        Marks the broker as finished and deletes it from the dictionary.
        Used when memory needs to be freed immediately.

        Args:
            run_id (str): Unique run identifier
        """
        if run_id in self._brokers:
            self._brokers[run_id].mark_finished()
            del self._brokers[run_id]
            logger.debug(f"Removed broker for run {run_id}")

    async def start_cleanup_task(self) -> None:
        """Start a background task to clean up old brokers

        Called from the lifespan event on FastAPI app startup.
        Creates a background task to periodically clean up finished brokers.

        Note:
            - Does not create a new task if one is already running or not finished
        """
        if self._cleanup_task is None or self._cleanup_task.done():
            self._cleanup_task = asyncio.create_task(self._cleanup_old_brokers())

    async def stop_cleanup_task(self) -> None:
        """Stop the background cleanup task

        Called from the lifespan event on FastAPI app shutdown.
        Cancels the running cleanup task and waits for it to complete.

        Note:
            - CancelledError is automatically ignored (normal shutdown)
        """
        if self._cleanup_task and not self._cleanup_task.done():
            self._cleanup_task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await self._cleanup_task

    async def _cleanup_old_brokers(self) -> None:
        """Background task to clean up old, finished brokers

        Runs every 5 minutes and deletes brokers that meet the following conditions:
        1. Execution is complete (finished flag is set)
        2. The queue is empty (all events have been consumed)
        3. More than 1 hour has passed since creation

        Workflow:
        1. Every 5 minutes, iterate through all brokers
        2. Identify brokers that meet the cleanup conditions
        3. Remove the identified brokers from memory
        4. Log errors and continue running if an error occurs

        Note:
            - This task runs continuously while the application is running
            - CancelledError is considered a normal shutdown
        """
        while True:
            try:
                await asyncio.sleep(300)  # Check every 5 minutes

                asyncio.get_event_loop().time()
                to_remove = []

                for run_id, broker in self._brokers.items():
                    # Delete brokers that are finished, empty, and older than 1 hour
                    if (
                        broker.is_finished()
                        and broker.is_empty()
                        and broker.get_age() > 3600  # 1 hour = 3600 seconds
                    ):
                        to_remove.append(run_id)

                for run_id in to_remove:
                    self.remove_broker(run_id)
                    logger.info(f"Cleaned up old broker for run {run_id}")

            except asyncio.CancelledError:
                # Normal shutdown signal
                break
            except Exception as e:
                logger.error(f"Error in broker cleanup task: {e}")


# Global broker manager instance (singleton pattern)
# This instance is used throughout the application to access per-run brokers
broker_manager = BrokerManager()
