"""SQLAlchemy ORM setup for Agent Protocol metadata persistence.

This module defines the core database models for Open LangGraph.
LangGraph manages conversation state with its own checkpointer,
and the ORM models in this module store only Agent Protocol metadata.

Main components:
- `Base`: Base class for all ORM models (declarative base).
- `Assistant`: Assistant definitions (graph ID, settings, user info).
- `AssistantVersion`: Tracks assistant version history.
- `Thread`: Conversation thread metadata (state, user info).
- `Run`: Execution history (input/output, state, timestamps).
- `RunEvent`: Stores SSE events for streaming playback.
- `async_session_maker`: AsyncSession factory.
- `get_session`: Dependency helper for FastAPI routers.

Usage:
    from ...core.orm import get_session, Assistant

    @router.get("/assistants")
    async def list_assistants(session: AsyncSession = Depends(get_session)):
        result = await session.execute(select(Assistant))
        return result.scalars().all()
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any

from sqlalchemy import (
    TIMESTAMP,
    ForeignKey,
    Index,
    Integer,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base class for all ORM models."""

    pass


class Assistant(Base):
    """ORM model for an Assistant definition.

    An assistant is an executable entity that combines a specific LangGraph graph
    with a set of configurations. Users can create multiple assistants to run the
    same graph with different settings.

    Key fields:
    - assistant_id: Unique identifier (UUID, auto-generated by the DB).
    - graph_id: The ID of the LangGraph graph to execute (defined in open_langgraph.json).
    - name: User-specified name for the assistant.
    - config: LangGraph execution settings (JSONB).
    - context: Graph runtime context (JSONB).
    - version: Version number (defaults to 1).
    - metadata_dict: Additional metadata (JSONB).
    """

    __tablename__ = "assistant"

    # TEXT type PK, auto-generated on the DB side with uuid_generate_v4()
    assistant_id: Mapped[str] = mapped_column(
        Text, primary_key=True, server_default=text("uuid_generate_v4()::text")
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    graph_id: Mapped[str] = mapped_column(Text, nullable=False)
    config: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    context: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    metadata_dict: Mapped[dict[str, Any]] = mapped_column(
        JSONB, server_default=text("'{}'::jsonb"), name="metadata"
    )
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))

    # Indexes for performance optimization
    # - user_id: Optimizes queries for assistants by user.
    # - (user_id, assistant_id): Ensures uniqueness.
    # - (user_id, graph_id, config): Prevents duplicates with the same configuration.
    __table_args__ = (
        Index("idx_assistant_user", "user_id"),
        Index("idx_assistant_user_assistant", "user_id", "assistant_id", unique=True),
        Index(
            "idx_assistant_user_graph_config",
            "user_id",
            "graph_id",
            "config",
            unique=True,
        ),
    )


class AssistantVersion(Base):
    """ORM model for tracking assistant version history.

    Whenever an assistant is updated, its previous version is stored in this table.
    This allows users to roll back to a previous version or view the change history.

    Composite PK: (assistant_id, version)
    - assistant_id: Assistant identifier (FK, CASCADE DELETE).
    - version: Version number (1, 2, 3, ...).
    """

    __tablename__ = "assistant_versions"

    assistant_id: Mapped[str] = mapped_column(
        Text, ForeignKey("assistant.assistant_id", ondelete="CASCADE"), primary_key=True
    )
    version: Mapped[int] = mapped_column(Integer, primary_key=True)
    graph_id: Mapped[str] = mapped_column(Text, nullable=False)
    config: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    context: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))
    metadata_dict: Mapped[dict[str, Any]] = mapped_column(
        JSONB, server_default=text("'{}'::jsonb"), name="metadata"
    )
    name: Mapped[str | None] = mapped_column(Text)
    description: Mapped[str | None] = mapped_column(Text)


class Thread(Base):
    """ORM model for conversation thread metadata.

    A thread represents a single conversation session.
    The actual conversation messages and state are stored in the LangGraph checkpointer.
    This table only manages the thread's status (idle/busy/interrupted) and metadata.

    Status types:
    - idle: Waiting (ready to run).
    - busy: Running.
    - interrupted: Paused (Human-in-the-Loop).

    Key fields:
    - thread_id: Unique identifier (created by the client).
    - status: Current status.
    - metadata_json: Assistant/graph information, etc. (JSONB).
    - user_id: Owner (for multi-tenant isolation).
    """

    __tablename__ = "thread"

    thread_id: Mapped[str] = mapped_column(Text, primary_key=True)
    status: Mapped[str] = mapped_column(Text, server_default=text("'idle'"))
    # DB column name is 'metadata_json', ORM attribute is also mapped to 'metadata_json'
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata_json", JSONB, server_default=text("'{}'::jsonb")
    )
    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))

    # Optimization: Index for querying threads by user.
    __table_args__ = (Index("idx_thread_user", "user_id"),)


class Run(Base):
    """ORM model for an execution record.

    A Run is a single instance of an assistant execution within a specific thread.
    It stores execution metadata such as input, output, status, and timestamps.

    Status types:
    - pending: Waiting to be executed.
    - running: Currently executing.
    - streaming: Streaming output.
    - completed: Successfully completed.
    - failed: Failed.
    - cancelled: Cancelled.
    - interrupted: Paused (HITL).

    Key fields:
    - run_id: Unique identifier (UUID, auto-generated by the DB).
    - thread_id: The thread it belongs to (FK, CASCADE DELETE).
    - assistant_id: The assistant used (FK, CASCADE DELETE).
    - input: Execution input data (JSONB).
    - output: Execution result (JSONB).
    - config: LangGraph execution settings (JSONB).
    - context: Runtime context (JSONB).
    - error_message: Message if an error occurred.
    """

    __tablename__ = "runs"

    # TEXT type PK, auto-generated on the DB side with uuid_generate_v4()
    run_id: Mapped[str] = mapped_column(
        Text, primary_key=True, server_default=text("uuid_generate_v4()::text")
    )
    thread_id: Mapped[str] = mapped_column(
        Text, ForeignKey("thread.thread_id", ondelete="CASCADE"), nullable=False
    )
    assistant_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("assistant.assistant_id", ondelete="CASCADE")
    )
    status: Mapped[str] = mapped_column(Text, server_default=text("'pending'"))
    input: Mapped[dict[str, Any] | None] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    # config column: May not exist in some environments, so set to nullable.
    # If added via migration, it is already defined in the ORM.
    config: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    context: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    output: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    error_message: Mapped[str | None] = mapped_column(Text)
    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))

    # Indexes for performance optimization
    # - thread_id: For querying runs by thread.
    # - user_id: For querying runs by user.
    # - status: For filtering by status.
    # - assistant_id: For querying runs by assistant.
    # - created_at: For optimizing chronological sorting.
    __table_args__ = (
        Index("idx_runs_thread_id", "thread_id"),
        Index("idx_runs_user", "user_id"),
        Index("idx_runs_status", "status"),
        Index("idx_runs_assistant_id", "assistant_id"),
        Index("idx_runs_created_at", "created_at"),
    )


class RunEvent(Base):
    """ORM model for storing execution events (for SSE replay).

    This table stores all events that occur during Server-Sent Events (SSE) streaming.
    If a client disconnects and reconnects, the stored events can be replayed.

    Key fields:
    - id: Unique event ID (format: {run_id}_event_{seq}).
    - run_id: The ID of the run it belongs to.
    - seq: Sequence number (for ordering).
    - event: Event type (values, messages, end, etc.).
    - data: Event payload (JSONB).
    - created_at: Creation time.

    Cleanup policy:
    - The event_store service periodically deletes old events (default: older than 300 seconds).
    """

    __tablename__ = "run_events"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    run_id: Mapped[str] = mapped_column(Text, nullable=False)
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    event: Mapped[str] = mapped_column(Text, nullable=False)
    data: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), server_default=text("now()"))

    # Indexes for performance optimization
    # - run_id: For querying events by run.
    # - (run_id, seq): For optimizing sequence-based event replay.
    __table_args__ = (
        Index("idx_run_events_run_id", "run_id"),
        Index("idx_run_events_seq", "run_id", "seq"),
    )


# ---------------------------------------------------------------------------
# Session factory (for FastAPI dependency injection)
# ---------------------------------------------------------------------------

async_session_maker: async_sessionmaker[AsyncSession] | None = None


def _get_session_maker() -> async_sessionmaker[AsyncSession]:
    """Return a cached async_sessionmaker bound to the db_manager engine.

    This function lazily creates and caches the AsyncSession factory.
    It is used by FastAPI dependencies to create a new session for each request.

    Returns:
        async_sessionmaker: The AsyncSession factory.
    """
    global async_session_maker
    if async_session_maker is None:
        from .database import db_manager

        engine = db_manager.get_engine()
        async_session_maker = async_sessionmaker(engine, expire_on_commit=False)
    return async_session_maker


async def get_session() -> AsyncIterator[AsyncSession]:
    """Database session dependency for FastAPI routers.

    This function is used with FastAPI's Depends() to create a new
    AsyncSession for each request and automatically clean it up when the request is done.

    Usage example:
        @router.get("/assistants")
        async def list_assistants(session: AsyncSession = Depends(get_session)):
            result = await session.execute(select(Assistant))
            return result.scalars().all()

    Yields:
        AsyncSession: A per-request database session.
    """
    maker = _get_session_maker()
    async with maker() as session:
        yield session
